import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { RestrictionAuth } from "@/components/Authentication/RestrictionAuth";
//import Sidebar from "@/components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ensoil",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
       <link rel="icon" href="/logo.png" type="image/png" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* <RestrictionAuth> */}
        <div className="flex h-screen">
          <main className="flex-1">
            {children}
          </main>
        </div>
        {/* </RestrictionAuth> */}
      </body>
    </html>
  );
}
